services:
  db:
    image: postgres:15
    container_name: eshop_db
    environment:
      POSTGRES_DB: eshop
      POSTGRES_USER: eshop_user
      POSTGRES_PASSWORD: eshop_pass
    ports:
      - "5435:5432"
    volumes:
      - eshop_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: eshop_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8088:80"
    depends_on:
      - db

volumes:
  eshop_data:
